inhibit_all_warnings!
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'VictorDemo' do

pod 'MJRefresh',                                   '~> 3.1'   # The easiest way to use pull-to-refresh
pod 'MJExtension',                                 '~> 3.0'   # The fastest and most convenient conversion between JSON and model
pod 'IQKeyboardManager',                           '~> 4.0'   # 防止键盘挡住输入框, 引入项目即可生效
pod 'NSObjectExtend',                              '~> 1.8'   # NSObject 系列类添扩展
pod 'Masonry',                                     '~> 1.0'   # 自动布局框架
pod 'ReactiveCocoa',                               '~> 2.5'   # 响应式编程框架
pod 'LCNetwork',                                   '~> 1.2'   # 网络请求框架
pod 'YYWebImage',                                  '~> 1.0'   # 加载网络图片
pod 'SVProgressHUD',                               '~> 2.0'   # 提示框
pod 'MyLayout',                                    '~> 1.2'   # iOS界面布局库,基于对frame属性
pod 'FMDB',                                        '~> 2.6'   # 数据库工具
pod 'SDCycleScrollView',                           '~> 1.6'   # 自动轮播图片
pod 'ZYQAssetPickerController',                    '~> 1.0'   # 图库选图
pod 'RSKImageCropper',                             '~> 1.5'   # RSKIMAGECROPPER图片裁剪

end

target 'VictorDemoTests' do

end

target 'VictorDemoUITests' do

end
